// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Goo5PW1n7wlvNVRw-tPcKbpMNSjRIbw',
    appId: '1:412917315969:web:1b9978f2f7a3dcdf569080',
    messagingSenderId: '412917315969',
    projectId: 'kitahack-sleeping-beauties',
    authDomain: 'kitahack-sleeping-beauties.firebaseapp.com',
    storageBucket: 'kitahack-sleeping-beauties.firebasestorage.app',
    measurementId: 'G-6WRX25H31Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ZzowNPvfDNmKbIBj09CwLwNu0mvCIdg',
    appId: '1:412917315969:android:8fd91e925e23af4c569080',
    messagingSenderId: '412917315969',
    projectId: 'kitahack-sleeping-beauties',
    storageBucket: 'kitahack-sleeping-beauties.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDisGDzx0jzFCGTKZ97VNomwuaUbFlWY5s',
    appId: '1:412917315969:ios:f3a23b3dea176c2d569080',
    messagingSenderId: '412917315969',
    projectId: 'kitahack-sleeping-beauties',
    storageBucket: 'kitahack-sleeping-beauties.firebasestorage.app',
    androidClientId: '412917315969-8g0stbi69gaafhr36cbdhicdapejvqo4.apps.googleusercontent.com',
    iosClientId: '412917315969-mire77t6f5j68oa1ueovmm3gjbson8ac.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDisGDzx0jzFCGTKZ97VNomwuaUbFlWY5s',
    appId: '1:412917315969:ios:f3a23b3dea176c2d569080',
    messagingSenderId: '412917315969',
    projectId: 'kitahack-sleeping-beauties',
    storageBucket: 'kitahack-sleeping-beauties.firebasestorage.app',
    androidClientId: '412917315969-8g0stbi69gaafhr36cbdhicdapejvqo4.apps.googleusercontent.com',
    iosClientId: '412917315969-mire77t6f5j68oa1ueovmm3gjbson8ac.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Goo5PW1n7wlvNVRw-tPcKbpMNSjRIbw',
    appId: '1:412917315969:web:7068fb2e2dadcc9d569080',
    messagingSenderId: '412917315969',
    projectId: 'kitahack-sleeping-beauties',
    authDomain: 'kitahack-sleeping-beauties.firebaseapp.com',
    storageBucket: 'kitahack-sleeping-beauties.firebasestorage.app',
    measurementId: 'G-JCZSSYKDYM',
  );
}
